#!/bin/bash

filter='abusech'
rundir='/home/ostrichbot/security/'
download=$rundir'/'$filter'.list'
url='https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt'

# get latest black list
curl -G $url > $download

# Create ipset rule
ipset -N $filter iphash
ipset flush $filter

# Load drop list into ipset
while read line;
do
        ip_block="$(grep -oE '^([0-9]{1,3}\.){3}[0-9]{1,3}(/[0-9]{1,2})?' <<< $line)"
        ipset -A $filter $ip_block
done < $download

# save ipset
ipset save -file /etc/iptables/ipset
